#!/usr/bin/env bun
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { ERROR_CATEGORIES } from './config/error-categories'

const root = join(import.meta.dir, '..')
const target = join(root, 'references', 'error-codes.md')

/** Every literal error code thrown by the controller, with the files that throw it (used by checks). */
export function collectErrorCodes(): Map<string, Set<string>> {
  const codes = new Map<string, Set<string>>()
  // Codes are thrown as `new Error`, as bare `Error(...)`, or through a local `fail(code, …)`
  // helper. All three spellings count: a code the catalog misses is a diagnostic nobody can look up.
  const pattern = /(?:new Error|\bError|\bfail)\(\s*[`'"]([A-Z][A-Z0-9]*(?:_[A-Z0-9]+)+)/g
  for (const path of new Bun.Glob('scripts/**/*.ts').scanSync({ cwd: root })) {
    if (path.includes('/check-') || path.endsWith('render-error-catalog.ts')) continue
    const source = readFileSync(join(root, path), 'utf8')
    const matches = [...source.matchAll(pattern)]
    for (const match of matches)
      codes.set(match[1]!, (codes.get(match[1]!) ?? new Set()).add(path.replace(/^scripts\//, '')))
  }
  return codes
}

/** Render the catalog grouped by category: remediation first, then every code in the category. */
export function renderErrorCatalog(): string {
  const codes = collectErrorCodes()
  const categoryOf = (code: string) =>
    Object.entries(ERROR_CATEGORIES).find(([, entry]) =>
      entry.prefixes.includes(code.split('_')[0]!)
    )?.[0] ?? 'other'
  const groups = new Map<string, string[]>()
  for (const code of [...codes.keys()].sort())
    groups.set(categoryOf(code), [...(groups.get(categoryOf(code)) ?? []), code])
  const lines = [
    '# Error codes',
    '',
    `Generated by \`bun scripts/render-error-catalog.ts\` from ${codes.size} literal codes thrown under \`scripts/\`; do not edit by hand. A code's text after \`:\` is detail, not part of the code. Look up the category first: its remediation is the first thing to try.`,
    ''
  ]
  for (const key of [...Object.keys(ERROR_CATEGORIES), 'other']) {
    const list = groups.get(key)
    if (!list?.length) continue
    const entry = ERROR_CATEGORIES[key]
    lines.push(`## ${entry?.title ?? 'Other'} (${list.length})`, '')
    lines.push(
      entry
        ? `Remediation: ${entry.remediation}`
        : 'Remediation: read the matching role reference; search `scripts/` for the code to find where it is raised.',
      ''
    )
    lines.push(list.map((code) => `\`${code}\``).join(' · '), '')
  }
  return lines.join('\n')
}

if (import.meta.main) {
  const next = renderErrorCatalog()
  if (process.argv.includes('--check')) {
    if (!existsSync(target) || readFileSync(target, 'utf8') !== next) {
      console.error('ERROR_CATALOG_STALE: run bun scripts/render-error-catalog.ts')
      process.exit(1)
    }
    console.log('PASS: error catalog current')
  } else {
    writeFileSync(target, next)
    console.log(`wrote ${target}`)
  }
}
